package app.reisebus.reisebus_api.common.tenancy

import org.hibernate.engine.jdbc.connections.spi.MultiTenantConnectionProvider
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Component
import java.sql.Connection
import javax.sql.DataSource


/**
 * Switches search_path per tenant: tenant_<slug>_<12 hex>, platform, public
 *
 * - "platform" is always in the path, so platform tables resolve in every tenant session.
 * - "public" holds event_publication (Spring Modulith).
 * - The path is reset on release, otherwise pooled connections leak the previous tenant.
 */
@Component
class SchemaConnectionProvider(
    private val dataSource: DataSource,
    @Value($$"${app.tenancy.platform-schema:platform}") private val platformSchema: String,
) : MultiTenantConnectionProvider<String> {

    override fun getAnyConnection(): Connection = dataSource.connection

    override fun releaseAnyConnection(connection: Connection) = connection.close()

    override fun getConnection(tenantIdentifier: String): Connection {
        // Defence in depth: the name is generated by PlatformService, but never trust it near SQL.
        require(VALID_SCHEMA.matches(tenantIdentifier)) { "Invalid schema name: $tenantIdentifier" }
        val connection = dataSource.connection
        try {
            setSearchPath(connection, searchPathFor(tenantIdentifier))
        } catch (e: Exception) {
            connection.close()
            throw e
        }
        return connection
    }

    override fun releaseConnection(tenantIdentifier: String, connection: Connection) {
        connection.use { connection ->
            setSearchPath(connection, searchPathFor(platformSchema))
        }
    }

    override fun supportsAggressiveRelease(): Boolean = false
    override fun isUnwrappableAs(unwrapType: Class<*>): Boolean = false
    override fun <T> unwrap(unwrapType: Class<T>): T = throw UnsupportedOperationException()

    private fun searchPathFor(schema: String) =
        if (schema == platformSchema) "$platformSchema, public" else "$schema, $platformSchema, public"

    // set_config with a bind parameter: no string concatenation into SQL.
    private fun setSearchPath(connection: Connection, path: String) {
        connection.prepareStatement("SELECT set_config('search_path', ?, false)").use {
            it.setString(1, path)
            it.execute()
        }
    }

    private companion object {
        // "platform" or "tenant_" + slug + "_" + 12 hex chars; Postgres identifiers are max 63 chars.
        val VALID_SCHEMA = Regex("^(platform|tenant_[a-z0-9_]{1,56})$")
    }
}
