spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reisebus_dev
    username: reisebus
    password: reisebus
  jpa:
    properties:
      hibernate:
        order_updates: true
        jdbc:
          batch_size: 10
  liquibase:
    contexts: dev
app:
  tenancy:
    migrate-on-startup: true