spring:
  application:
    name: reisebus-api
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: prod
  modulith:
    events:
      republish-outstanding-events-on-restart: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:http://localhost:8081/realms/reisebus-dev}
app:
  base-domain: ${BASE_DOMAIN:http://localhost:8080}
  tenancy:
    migrate-on-startup: false
    platform-schema: platform
